### ISSUE TITLE
Endtime selection in 24 time format bugged

### ISSUE THREAD

**Issue by Phistr90** [poapxyz/poap-vote#11]
Hi,

the endtime selection is bugged. It says it should be 24h format in local time but it only gives options for 0-12 for the hour.

It appears that it is still 12h format without any selector of am/pm. Because choosing 12:00 let to 12am for me not 12pm.

**Comment by ragonzal** [comment]
Hi @Phistr90, thanks for catching the bug.
Just for you to know, this is an old repo, this is the correct one: https://github.com/poap-xyz/poap-vote-v2
I'll be deploying the fix in the next minutes.
